### ISSUE TITLE
Error sending a message to another user ERR: -32098:panic occured.

### ISSUE THREAD

**Issue by ghost** [civilware/dM#1]
![Screenshot 2022-07-02 at 23-47-05 DERO Message](https://user-images.githubusercontent.com/86203717/177026739-d73d1c73-74f0-4ebb-b1ba-e3fecdf19012.png)

Characters Remaining: 477
Response: ERR: -32098:panic occured. stack trace goroutine 631050483 [running]: runtime/debug.Stack() /home/github/local/go/src/runtime/debug/stack.go:24 +0x65 github.com/deroproject/derohe/cmd/derod/rpc.GetEncryptedBalance.func1() /tmp/derohe/derohe96a/cmd/derod/rpc/rpc_dero_getencryptedbalance.go:37 +0x35 panic({0x9bf760, 0xc0000680a0}) /home/github/local/go/src/runtime/panic.go:1038 +0x215 github.com/deroproject/derohe/cmd/derod/rpc.GetEncryptedBalance({_, _}, {{0xc0422b80a0, 0x47}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}) /tmp/derohe/derohe96a/cmd/derod/rpc/rpc_dero_getencryptedbalance.go:43 +0x994 reflect.Value.call({0x9c6120, 0xaec008, 0xc00388ada0}, {0xa6310c, 0x4}, {0xc00cbe6ae0, 0x2, 0xc00050adb0}) /home/github/local/go/src/reflect/value.go:543 +0x814 reflect.Value.Call({0x9c6120, 0xaec008, 0xc00cbe6a50}, {0xc00cbe6ae0, 0x2, 0x2}) /home/github/local/go/src/reflect/value.go:339 +0xc5 github.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func10({0xb99200, 0xc00cbe6a50}, 0xf58520) /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/handler/handler.go:244 +0xed github.com/creachadair/jrpc2/handler.Func.Handle(0xf58140, {0xb99200, 0xc00cbe6a50}, 0x1) /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/handler/handler.go:25 +0x2f github.com/creachadair/jrpc2.(*Server).invoke(0xc0109fe0e0, {0xb99158, 0xc00ca03000}, {0xb8c6a0, 0xc000481c60}, 0xc00ca02fc0) /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/server.go:379 +0x17e github.com/creachadair/jrpc2.(*Server).dispatch.func1() /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/server.go:230 +0x1b1 github.com/creachadair/jrpc2.(*Server).serve.func1() /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/server.go:152 +0x5a created by github.com/creachadair/jrpc2.(*Server).serve /tmp/derohe/derohe96a/vendor/github.com/creachadair/jrpc2/server.go:150 +0x29

**Comment by Nelbert442** [comment]
Will look into as I can. Thanks.

**Comment by Nelbert442** [comment]
@secretnamebasis - based on what's in the destination, you're using an integrated address. Just wanted to confirm this. I have been unsuccessful in trying to replicate your issue, but do continue to investigate as I can. If you could provide potentially any steps taken to get to this point I'll see if I can assist.

I've added locally a handle for integrated addresses regardless of it appearing to have an issue or not, but going to error on the side and say that could potentially be because of it. The go panic is an odd one in regards to what potentially would even be calling get encrypted balance rpc call. But will keep poking through . 

Sorry about the issue!

**Comment by ghost** [comment]
I tried to recreate this error. 
I wasn't using an integrated address.
I think I ran something like go run, or something to that effect (I wish I made better documentation of my steps to create the error). 
I was, however, able to get everything up and running with the following

git clone https://github.com/civilware/dM
cd dM
chmod +rwx build_all.sh
./build_all
cd deromessage_linux_amd64/
./deromessage_linux_amd64 --help
(was really interested in how I would do user:pass login authentication here, found none)
./dero-wallet-cli --remote --rpc-server
./deromessage-linux-amd64 --rpc-server-address 127.0.0.1:10103  --daemon-rpc-address 89.38.99.117:10102
opened browser
in address bar: `127.0.0.1:8080`
Wrote message to hot-wallet
sent message
In the terminal it read

```
2022/07/06 22:16:14 [API-sendMessageCall] Received message to be sent/processed: {dero1qyvqpdftj8r6005xs20rnflakmwa5pdxg9vcjzdcuywq2t8skqhvwqglt6x0g This is a message }
2022/07/06 22:16:14 [processSendingMessages] Checking 'd4787124f97d6d' to see if it is already used in SC.
2022/07/06 22:16:15 [checkUserKeyResults] Returned string - &{[] [NOT AVAILABLE err: leaf not found: collision, keyhash 8d14e4bbff75f0e852181726b743127af3db5c3f38f41ee069e1bc17a16042de not found, keyhash in ram 83eb3683003244df43dba718ae1c2d1ee5d24e4b18c01c22b4e7a8fee7ebba72: leaf not found] [] map[] map[] map[] 0  OK}
2022/07/06 22:16:15 [processSendingMessages] Var 'd4787124f97d6d' is not already defined in SC, proceeding.
2022/07/06 22:16:15 [processSendingMessages] original string (len: 17): 
This is a message
2022/07/06 22:16:15 [encryptAndSend] Encrypted text: [218 140 60 237 139 107 210 99 19 242 143 8 217 126 46 251 156 255 9 135 2 227 18 35 24 28 159 211 211 84 229 15 114 42 19 32 22 121 241 86 236 188 146 89 228 84 33 126 5 49 163 61 211 76 168 25 72]
2022/07/06 22:16:15 [encryptAndSend] Ciphertext: da8c3ced8b6bd26313f28f08d97e2efb9cff098702e31223181c9fd3d354e50f722a13201679f156ecbc9259e454217e0531a33dd34ca81948
2022/07/06 22:16:15 [encryptAndSend] gas estimate results: {20000 337 OK}
2022/07/06 22:16:15 [processSendingMessages] Sending transfers tx...
2022/07/06 22:16:19 [sendTx] Tx sent successfully - txid: 9a647a86f23a2090f06bb5dcfc5540ebacc8f02ec90cba6a7baf3323b4da2ca3
2022/07/06 22:16:19 [Graviton-StoreSentTX] Storing &{1657167379 dero1qyvqpdftj8r6005xs20rnflakmwa5pdxg9vcjzdcuywq2t8skqhvwqglt6x0g d4787124f97d6d [195 138 49 26 234 149 23 213 123 80 80 59 217 119 185 195 141 179 111 172 62 164 214 22 253 92 165 242 254 95 128 171]}
2022/07/06 22:16:19 [sendTx] TX Sent and stored
```

In rpc-wallet
```
06 Jul 22 22:16 MDT Height 605998 TopoHeight 605998 transaction 9a647a86f23a2090f06bb5dcfc5540ebacc8f02ec90cba6a7baf3323b4da2ca3 spent 0.00001 DERO Destination: dero1qyvqpdftj8r6005xs20rnflakmwa5pdxg9vcjzdcuywq2t8skqhvwqglt6x0g Proof: deroproof1qyxncqknk2g8rzg5qa8esqfxwd9xmkrtfgl9mt6nr5c47cwvl82zkq9zvfyyskpqh82l0nkksr4facpca88j8vlnnu4a9gwga4dq24w39ancu573w6lky4j4qy0nxleh RPC CALL arguments [Name:C Type:string Value:'d4787124f97d6d/c38a311aea9517d57b50503bd977b9c38db36fac3ea4d616fd5ca5f2fe5f80ab' Name:D Type:uint64 Value:'3901339073161396224' Name:S Type:uint64 Value:'3901339073161396224'] 
```
In hot-wallet

```
06 Jul 22 22:16 MDT Height 605998 TopoHeight 605998 transaction 9a647a86f23a2090f06bb5dcfc5540ebacc8f02ec90cba6a7baf3323b4da2ca3 received 0.00001 DERO Proof: deroproof1qyxncqknk2g8rzg5qa8esqfxwd9xmkrtfgl9mt6nr5c47cwvl82zkq9zvfyyskpqh82l0nkksr4facpca88j8vlnnu4a9gwga4dq24w39ancu573w6lky4j4qy0nxleh RPC CALL arguments [Name:C Type:string Value:'d4787124f97d6d/c38a311aea9517d57b50503bd977b9c38db36fac3ea4d616fd5ca5f2fe5f80ab' Name:D Type:uint64 Value:'3901339073161396224' Name:S Type:uint64 Value:'3901339073161396224'] 
```

**Comment by Nelbert442** [comment]
```
./deromessage_linux_amd64 --help
(was really interested in how I would do user:pass login authentication here, found none)
```

Rpc auth will be added in future. 

Glad it worked through . Thanks!
